<?php
/**
 * Copyright (c) 2023
 * MIT License
 * Module AnassTouatiCoder_BackToTop
 * Author Anass TOUATI anass1touati@gmail.com
 */
use Magento\Framework\Escaper;
use Magento\Framework\View\Element\Template;

/** @var Template $block */
/** @var Escaper $escaper */
?>
<span id="backToTop-component" class="go-top fadeout" style="">
    <span class="backToTop-decoration"></span>
    <?= $escaper->escapeHtml('Back to top') ?>
</span>

<script>
    {
        document.querySelector('#backToTop-component').addEventListener('click', (e) => {
            e.preventDefault();
            window.scrollTo({top: 0, behavior: 'smooth'});
        });

        window.addEventListener('scroll', function(e) {
            var backToTop = document.querySelector('#backToTop-component');
            if (window.scrollY > 150) {
                backToTop.classList.remove('fadeout')
                backToTop.classList.add('fadein')
            } else {
                backToTop.classList.remove('fadein')
                backToTop.classList.add('fadeout')
            }
        });
    }
</script>
