<?php
/**
 * Copyright (c) 2023
 * MIT License
 * Module AnassTouatiCoder_BackToTop
 * Author Anass TOUATI anass1touati@gmail.com
 */
use Magento\Framework\Escaper;
use AnassTouatiCoder\BackToTop\Block\BackToTop;

/** @var BackToTop $block */
/** @var Escaper $escaper */

?>
<?php if ($block->getIsEnabledInPage()): ?>
    <span id="backToTop-component" class="go-top fadeout" style="display: none">
        <span class="backToTop-decoration"></span>
    </span>
    <script>
        window.backToTopConfig = <?= /** No escape we are sending JSON object */$block->getConfigData() ?>;
    </script>
<?php endif;?>
